### PR TITLE
WebSocket Channel Support

### PR DESCRIPTION
**Pull request by adamdriscoll**
Client\Server support for WebSockets using OWIN

### CODE REVIEW

**Comment by daviwil** [comment]
This is exciting, will be really cool to use it for new integrations!

Looks like after accepting another PR this one needs to be updated.  When you get a chance, can you rebase against the current state of master and push the PR again?  No rush at all.

Thanks man!

**Comment by adamdriscoll** [comment]
Sure thing!

**Comment by daviwil** [comment]
This is strange, it looks like the rebase has pulled in Keith's latest commit as part of your PR...  Did you get any weird warnings or errors while performing the rebsae?

**Comment by adamdriscoll** [comment]
Yeah. I have no idea how that happened. Trying to fix now.

**Comment by adamdriscoll** [comment]
Replaced by: https://github.com/PowerShell/PowerShellEditorServices/pull/91

**Pull request closed without merging**
