### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by daviwil**

### CODE REVIEW

**Comment by daviwil** [comment]
Yeah, I keep putting off making a real solution for that :)

**Comment by rkeithhill** [comment]
I'm guessing the tests file could probably use reflection to get the version number?  If so, perhaps I can implement that.

**Comment by daviwil** [comment]
I think the best solution would be for it to read it from the .psd1 file since we're loading based on the module version.  Shouldn't be too hard to grab it out of the .psd1 contents with a regex

**Comment by rkeithhill** [comment]
That'll work too.

**Pull request merged**
