### PR TITLE
Fix issue where MS Dynamics CRM

### PR DESCRIPTION
**Pull request by rkeithhill**
redefines set-content, breaks Start-PSES

Fixes https://github.com/PowerShell/vscode-powershell/issues/1331

I wish we didn't have to module qualify command names like this but
we've been bitten several times now by overridden commands.

One concern I have is testing this due to it needing to be signed.

### CODE REVIEW

**Comment by rjmholt** [comment]
Wow that's annoying. But it seems necessary...

**Comment by rjmholt** [comment]
Do we need to modify PowerShellEditorServices.psm1 as well?

**Comment by rkeithhill** [comment]
Yes.  Good catch!  I'll get that in a bit later tonight.

**Comment by tylerl0706** [comment]
It might be worth double checking the scripts that we use for remoting as well. psedit and such.

**Comment by rkeithhill** [comment]
> I feel like there should be a PSSA rule on redefining core cmdlets

That's a good idea.  You should post that in the PSSA repo.

**Comment by rkeithhill** [comment]
This is relevant to this issue -  https://github.com/PowerShell/PowerShell/issues/7040#issuecomment-396957172

**Comment by tylerl0706** [comment]
https://github.com/PowerShell/PSScriptAnalyzer/issues/1023 did the thing!

**Comment by kilasuit** [comment]
Whilst I know this is merged I would reccommend for defensive reasons across all of PSES you Module Qualify commands to ensure no one else breaks your functionality, perhaps in a similar way to how Pester does it

**Comment by TylerLeonhardt** [comment]
> perhaps in a similar way to how Pester does it

can you elaborate on this?

**Comment by rjmholt** [comment]
> can you elaborate on this?

[Pester defines a table of safe commands ahead of time](https://github.com/pester/Pester/blob/5b4860f7baf72abd66da2c5a9ae608fd654e4d29/Pester.psm1#L28-L87) because it has to be safe for mocking. That affects startup time and depends on 

>  I would reccommend for defensive reasons across all of PSES you Module Qualify commands to ensure no one else breaks your functionality

Precisely what this PR did, and we've done a bit more since. We also fully qualified native utils by path, since people like to install their own. There may still be some outliers left in things like C#-invoked PowerShell, but it's the kind of thing we're shaving down over time.

**Pull request merged**
