### PR TITLE
Release 1.2.1

### PR DESCRIPTION
**Pull request by daviwil**

### CODE REVIEW

**Comment by daviwil** [comment]
Don't worry @rkeithhill, not planning to merge just yet :)

**Comment by rkeithhill** [comment]
I've got a partial fix that is ready to go.

**Comment by daviwil** [comment]
Partial fix works for me!

**Comment by daviwil** [comment]
No rush man!

**Comment by rkeithhill** [comment]
PR pushed.  Waiting for build results.

**Pull request merged**
