### PR TITLE
Remove leftover csproj reference to already removed project in test project PowerShellEditorServices.Test.Host.csproj

### PR DESCRIPTION
**Pull request by bergmeister**

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
The PSES.Host project is a reallllly old proj before the move to Omnisharp.

It was removed/merged into PowerShellEditorServices.csproj.

Even well before that, these .Host tests were disabled because they were poor quality.

For now they serve as a reference, but they're dead tests at the moment.

**Comment by bergmeister** [comment]
Should we remove the reference then? The `dotnet restore` error caused by it is annoying/confusing to see. If tests are not being run, I'd delete the code then

**Comment by TylerLeonhardt** [comment]
> Should we remove the reference then?

Yes lets do this at least for now. We'll delete the code after I've had the time to inspect it for anything salvageable

**Comment by andschwa** [comment]
LOL a year later I wasted a day determining that all the problems I was looking at weren't new...just that this code was dead and left in the repo instead of being relegated to the Git history.

**Pull request merged**
