### PR TITLE
Implemented -LanguageServiceOnly switch.

### PR DESCRIPTION
**Pull request by dkattan**
In situations where the Debug server is not necessary, it is not possible to shutdown PSES as it hangs here:
https://github.com/PowerShell/PowerShellEditorServices/blob/96a8207db0ad3d692a8429de3373e65d0fa0624b/src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs#L186

### CODE REVIEW

**Comment by dkattan** [comment]
Hey @andschwa would you mind reviewing this and getting it merged?

**Comment by dkattan** [comment]
@JustinGrote Would you mind reviewing this?

**Review by andschwa — APPROVED** [review]
Merging!

**Comment by dkattan** [comment]
Looks like there's some sort of transient error on MacOS. I made a small change to re-trigger CI which invalidated auto-merge. Evidently CI re-runs automatically and when it did all checks passed:

image

Anyway, @andschwa you'll likely need to merge it when you get back from vacation

**Comment by dkattan** [comment]
Hey @andschwa I pushed a commit and invalidated your auto-merge. Can you get this merged in?

**Pull request merged**
