### PR TITLE
add ADOPTERS.md

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Create ADOPTERS.md allowing contributors to add themselves

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
@SteveL-MSFT can you pre-fill this with what's in https://github.com/PowerShell/PowerShellEditorServices#powershell-language-server-protocol-clients-using-powershell-editor-services

**Comment by SteveL-MSFT** [comment]
@TylerLeonhardt the intent is for the adopters to submit the PR with their own language, not for us to fill it out

**Comment by TylerLeonhardt** [comment]
I see so does this file light up some GitHub graph magic or something or is this something we're starting?

**Comment by SteveL-MSFT** [comment]
@TylerLeonhardt I'm not aware of any GitHub integration.  This is a common file used in other OSS projects.

**Comment by TylerLeonhardt** [comment]
@SteveL-MSFT so should we reach out to our partners and say "hey can you add yourself to this list?"

**Comment by TylerLeonhardt** [comment]
cc @SydneyhSmith

**Comment by SteveL-MSFT** [comment]
@TylerLeonhardt yes, once this is merged

**Comment by TylerLeonhardt** [comment]
@SteveL-MSFT should vscode-powershell have one of these as well?

**Comment by SteveL-MSFT** [comment]
@TylerLeonhardt wouldn't that just be a subset of PSES?

**Comment by TylerLeonhardt** [comment]
I guess so... But PSES is an implementation detail for like... vscode and Azure Data Studio.

Then there's like... The Azure Functions extension that depends on the PowerShell extension for debugging.

**Comment by SteveL-MSFT** [comment]
I don't think there's an inherent issue with a separate one for vs-ps extension.  It just seemed like that one would be much more limited in adopters.

**Pull request merged**
