### PR TITLE
PSES side changes for issue #96 - support x86/x64 debugging.

### PR DESCRIPTION
**Pull request by rkeithhill**
Besides **all** the awesome work @adamdriscoll did to enable this; there are some changes that need to be made to package.json in the vscode repo.  In order to support those changes, we need a different filename for the x86 batch file that launches the x86 debug host.

### CODE REVIEW

**Comment by rkeithhill** [comment]
@daviwil - is there somewhere this renamed file needs to be added to ensure it is part of the package and installed into the extension's bin dir?

**Comment by rkeithhill** [comment]
I'm not sure the VSCode tweak is going to make it into the next release.  I'm going to hold off on the VSCode change until I can verify the VSCode fix is in place.  But I think this PR is still good to merge (shouldn't hurt anything even if it isn't being used yet).

**Comment by daviwil** [comment]
Yeah, I was thinking about the packaging issue recently...  I think it makes sense for there to be a single PowerShellEditorServices.Host NuGet package which contains both host EXEs and respective cmd files.  Right now I think the only way to accomplish that will be to change the `src\PowerShellEditorServices.Host\PowerShellEditorServices.Host.nuspec` file to include all of the necessary files so that they're packaged up together.  

I believe this requires adding a `files` section under the root `package` node after `metadata`:

```xml
<files>
  <file src="bin\$configuration$\$id$.exe" target="lib\net45\" />
  <file src="bin\$configuration$\$id$.DebugAdapter.cmd" target="content\" />
  <file src="..\PowerShellEditorServices.Host.x86\bin\$configuration$\$id$.x86.exe" target="lib\net45\" />
  <file src="..\PowerShellEditorServices.Host.x86\bin\$configuration$\$id$.DebugAdapter.x86.cmd" target="content\" />
</files>
```

More info: http://docs.nuget.org/Create/Nuspec-Reference

You should be able to test this by running this command (note the .csproj at the end):

`.\.nuget\NuGet.exe pack src\PowerShellEditorServices.Host\PowerShellEditorServices.Host.csproj`

I actually just tried to replicate this and it worked fine for me.  Both DLLs and CMD files show up in the resulting NuGet package for me.  If you make this change, could you also delete the .nuspec file in `src\PowerShellEditorServices.Host.x86` so we don't end up with an extra NuGet package?

**Comment by rkeithhill** [comment]
Is this NuGet package what gets pushed to the VSCode gallery as the PSES extension?

**Comment by daviwil** [comment]
Nah, it's one step earlier in the chain where I publish NuGet packages of the binaries to NuGet.org.  I'm going to start using `Install-Package` to yank those from NuGet to package up the VS Code extension.

**Comment by rkeithhill** [comment]
OK, I'll commit to this branch so it all contained.  Might not get to this until tomorrow.

**Comment by daviwil** [comment]
No problem, thanks a lot for doing it!

**Comment by rkeithhill** [comment]
Man, that Platform=X64 environment variable bit me again.  Nuget.exe failed until I removed that env var from my console.  Anyway, the update to this PR for the requested nuspec changes have been pushed.

**Comment by daviwil** [comment]
Awesome, thanks for making the nuspec changes!  Merged.

**Pull request merged**
