### PR TITLE
Add ability to identify active signature and parameter

### LINKED ISSUE #34: Signature help request should be able to identify the parameter that the user is typing
In VS Code, the signature help window appears when the user is typing a command to give them hints about parameters.  

image

It also has the ability to highlight the current parameter while the user is typing.  The internal logic for finding parameter hints at the cursor should be able to determine which parameter the user is typing in and return its index so that the UI knows which parameter to highlight.

### PR DESCRIPTION
**Pull request by kapilmb**
Resolves #34

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/powershelleditorservices/257)

### CODE REVIEW

**Comment by daviwil** [comment]
Nice!  I'll try this out when I get to the office.  Let's meet up sometime today to talk about it.

**Comment by kapilmb** [comment]
Sure. 

Looks like some test cases are failing.  Will take care of it.

**Comment by daviwil** [comment]
The current test issues are probably related to the change I merged yesterday.  I'll investigate the core issue and get it fixed this week.

**Comment by daviwil** [comment]
Looks like you've made the changes we talked about, is this ready to be merged now?

**Pull request closed without merging**
