### PR TITLE
[Ignore] Update dotnet SDK to 3.0.100

### PR DESCRIPTION
**Pull request by rjmholt**
Current version on https://dot.net. Need it to build in Visual Studio.

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
yikes!

**Comment by bergmeister** [comment]
Rob is using Visual Studio 🤭? What happened to vim? 🤣

**Comment by rjmholt** [comment]
> Rob is using Visual Studio 🤭

For some reason the C# extension in VSCode really doesn't like PSES, and vim just isn't practical for C#, just like it wasn't for Java. JS, Python, etc. I used to use vim flawlessly with, but C#/Java are just too verbose. Also vim isn't great in the old school Windows console; hoping that will improve in the new terminal. If it were practical for me to use Ubuntu as a daily driver still, I'd have more vim emphasis.

**Comment by TylerLeonhardt** [comment]
@rjmholt ehem https://github.com/coc-extensions/coc-omnisharp 😎

**Comment by corbob** [comment]
> 
> 
> @rjmholt ehem https://github.com/coc-extensions/coc-omnisharp 😎

I mean if you're using neovim, perhaps you can just get it working??? https://twitter.com/Neovim/status/1194879302887559168

**Comment by rjmholt** [comment]
Closing in favour of the other one that took us to 2.1.802

**Pull request closed without merging**
