### PR TITLE
Add PSPossibleIncorrectUsageOfAssignmentOperator rule to default set of PSSA rules

### PR DESCRIPTION
**Pull request by AnyangoMango**

### CODE REVIEW

**Comment by SeeminglyScience** [comment]
I do like the idea of this rule, but it has too many false positives to be a default.  For example these will be flagged, but are valid:

```powershell
if ($a = $b) { }
if ($rs = [runspace]::DefaultRunspace) { }
```

**Comment by bergmeister** [comment]
This is a new rule that I added in the last release of PSSA (1.17.1). I added a lot of logic to reduce false positives.
Yes, as pointed out, there are still a few false positives but this is the nature of sophisticated code analysis that always requires human judgement (this is what suppression is for to document that the criticized pattern has been reviewed and approved). The given examples are prime examples of code that was potentially unintentional, I myself have forgotten that the equals operator in PowerShell is -eq and not = when switching between languages, which made me write this rule. I understand that this topic is controversial and opinionated though. Would anyone be interested in a poll to see what people think?

If PSES does not want rules that produce false positives then `PSUseDeclaredVarsMoreThanAssignments` should be removed from the set of default rules.

**Comment by SeeminglyScience** [comment]
I understand where you're coming from and I can definitely see how that rule would be very useful. My concern is that it's been shown frequently that a large portion of the community will view it only as an attack on their personal code style.  Granted that's true with all rules, but I think adding false positives to a common pattern that isn't actually discouraged wouldn't go over well.

> Would anyone be interested in a poll to see what people think?

 I don't think the type of folks I'm referring to are likely to be reached by a poll unfortunately.

> If PSES does not want rules that produce false positives then `PSUseDeclaredVarsMoreThanAssignments` should be removed from the set of default rules.

I think that's a bit different.  I'd consider false positives from that rule to be more of a technical limitation.  It's not too difficult to infer that it only happens in some scenarios, where the rule in question will appear frequently if you use that pattern a lot.

What about a version of the rule that only flags when the RHS is a constant?

**Comment by tylerl0706** [comment]
This makes me feel like we need to have a setting in vscode for like "PSSA strict mode" that gives you more rules turned on.

The PowerShell extension is probably one of the biggest clients of PSSA and we should try to give our users an easy way to take advantage of the cool features/rules of PSSA without force feeding them.

**Comment by bergmeister** [comment]
@SeeminglyScience The rule is already tweaked to not warn on e.g. the following pattern where the RHS is an expression or function as in `if ($a=Get-Item){ $a }'`. If the RHS is constant then the whole point of the rule is to warn as this might be unintentional, I do not see why one would assign a constant to a new variable INSIDE an if condition, maybe you can show me some example use cases?

@tylerl0706  Yes, we definitely need a way of using either the default rules or all rules with a new setting. At the moment, I recommend people to use a PSSA settings file with the content with just `@{}` in it to enable all rules. In my opinion all rules should be turned on by default because the majority of people are not aware of such customisations (and/or don't have the time for that), therefore the small subset of people that get annoyed by false positives can still fall back to the smaller set of rules using the new setting.
Even if some community members can feel attacked by false positives, it is not our job to be nice to them but rather make the better decision for the majority, which is to nag them with warnings, that is the whole point of the tool.

**Comment by SeeminglyScience** [comment]
@bergmeister 

> If the RHS is constant then the whole point of the rule is to warn as this might be unintentional, I do not see why one would assign a constant to a new variable INSIDE an if condition, maybe you can show me some example use cases?

I'm suggesting a rule that *only* warns when the RHS is a constant.  It's the only scenario where it is *definitely* a mistake.

> Even if some community members can feel attacked by false positives, it is not our job to be nice to them but rather make the better decision for the majority, which is to nag them with warnings, that is the whole point of the tool.

From the perspective of the tool being included in PSES, the point is to find obvious errors and optionally allow the user to standardize their code and the code of their projects.  I do think we should advertise that better and absolutely make it a lot easier to customize, but it is not the primary reason for it's inclusion.

**Comment by SteveL-MSFT** [comment]
Lots of good discussion here.  I agree that for new users, the mix-up of `-eq` and `=` is a common initial learning experience.  I also agree that false positives can create a bad experience for more experienced users.  Perhaps one option is to split the rule so that one rule only applies where the RHS is a constant as @SeeminglyScience suggests and is enabled by default (I believe this addresses the most common mistakes).  The existing rule that @bergmeister added stays as not default.

**Comment by TylerLeonhardt** [comment]
Let's try to address this in the RFC I have out now for an aggressive analysis mode:

https://github.com/PowerShell/PowerShell-RFC/pull/151/files

We can close this for now. Good discussions though!

**Pull request closed without merging**
