### PR TITLE
DO NOT MERGE Rebase attempt

### PR DESCRIPTION
**Pull request by TylerLeonhardt**

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
oof... this is rough. @SeeminglyScience + @rjmholt after fighting issues in the rebase we've hit a completely unusable experience on *nix... only with PSReadLine turned on of course...

**Comment by TylerLeonhardt** [comment]
Sorry, the issue is that any editor action (intellisense, codelens, F8, etc) needs you to hit any key in the PSIC before you actually see the action (intellisense, codelens, F8, etc).

My guess is that the rebase either included something that wasn't using the UnixConsoleEcho ReadKey, or reverted something that was fixed.

**Comment by SeeminglyScience** [comment]
@TylerLeonhardt Here's something to do for troubleshooting

1. Get PSES into a state when a background command is queue, but isn't processing due to the pending key press

1. Start debugging PSES with `justMyCode` turn **off**

1. Pause the debugger.  You should see a thread in the call stack that looks similar to this:

    1. [UnixConsoleOperations.ReadKey L58](https://github.com/PowerShell/PowerShellEditorServices/blob/9e3b4274971b1ac9d72f1c8d2e5a081209c4a30b/src/PowerShellEditorServices/Console/UnixConsoleOperations.cs#L58)
    1. [ConsoleProxy.UnixReadKey L82](https://github.com/PowerShell/PowerShellEditorServices/blob/9e3b4274971b1ac9d72f1c8d2e5a081209c4a30b/src/PowerShellEditorServices/Console/ConsoleProxy.cs)
    1. [PSReadLinePromptContext.AnonymousMethod L76](https://github.com/PowerShell/PowerShellEditorServices/blob/9e3b4274971b1ac9d72f1c8d2e5a081209c4a30b/src/PowerShellEditorServices/Session/PSReadLinePromptContext.cs#L76)
    1. `<something in PSReadLine>`

1. If not, then the delegate we give to PSReadLine either isn't being set early enough, or it just isn't being set

1. Also check all the threads for frames that are waiting on a console API

**Comment by rkeithhill** [comment]
Exactly what was the rebase here?  The `2.0.0.` branch rebased onto master?

**Comment by TylerLeonhardt** [comment]
Yeah. Adding the new master bits to 2.0.0

**Pull request closed without merging**
