### PR TITLE
Rkeithhill/script analysis profile path

### PR DESCRIPTION
**Pull request by rkeithhill**
Please check over when I'm converting an empty string settings path to the `null` that the ScriptAnalyzer.Initialize method is expecting.  I can either do it early in LanguageServerSettings or wait until right before we call Initialize.  Right now I'm doing it early but don't mind changing that strategy to defer the conversion.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershelleditorservices/209)

### CODE REVIEW

**Comment by rkeithhill** [comment]
Doh!  This PR will not compile until we pull in the change I made to PSScriptAnalyzer to add the extra profile parameter to the Initialize method.

**Comment by daviwil** [comment]
Looks like there's a build failure due to the Script Analyzer submodule not being synced to the commit of the latest release. You should be able to go into `submodules\PSScriptAnalyzer` and type `git pull origin` to get to the right commit. You'll need to commit the change that appears for that folder so that the submodule's HEAD is at the right commit. Let me know if you run into issues with that and I can assist.

**Comment by daviwil** [comment]
Ahhh crap, you saw it already :) let me read your message

**Comment by daviwil** [comment]
You'll need to also call `PublishScriptDiagnostics` once the setting has been changed so that the latest markers get pushed to the editor. If you look at the code for how I deal with the `enabled` setting being changed, I think you should see it.

**Comment by rkeithhill** [comment]
Ah, I saw the error but didn't know how to fix it.  I assumed you needed to do something to sync up with latest from the PSScriptAnalyzer team. I have been trying `git submodule update` but hadn't seen the change I made to PSScriptAnalyzer. So I hacked my working dir to make this work for me for testing.

**Comment by daviwil** [comment]
`git submodule update` only does something if a recent commit has changed the commit reference for the submodule.  To update the submodule's commit, you'll need to `cd submodules\PSScriptAnalyzer` and then `git pull origin master`.  After that you'll see that folder marked as modified in `git status`, so you should be able to do the following:

```
cd ..\..
git add submodules\PSScriptAnalyzer
git commit -m "Updated PSScriptAnalyzer to latest master."
```

Once you push that change the PR should build successfully.

**Comment by rkeithhill** [comment]
Since I'm still working off my fork, I think that needs to be `git pull PowerShell master`, right?  I named the upstream remote `PowerShell` before I knew about the convention of calling the original (not forked) repo `upstream`.

**Comment by daviwil** [comment]
This is actually to pull the origin of the PSScriptAnalyzer repo, so I think it'd be `origin` in that case.  `git pull`, etc work differently when you're in the folder of a submodule.  This is one of the reasons why I hate submodules...

**Comment by daviwil** [comment]
One thing you could check is the contents of `git remote -v` in the PSScriptAnalyzer submodule folder to see what the remote is named.  I imagine it's `origin` though.

**Comment by rkeithhill** [comment]
Ah I see.  Yes you are correct!  I ran `git pull origin master`.  I was 51 commits behind and it did a FF. Committed that.  Working on the publish diagnostics - no joy yet.

**Comment by daviwil** [comment]
Looks like one of the new profile tests failed, but ignore that for now, it's probably intermittent.  I've seen plenty of other builds pass recently.

**Comment by rkeithhill** [comment]
That particular test always fails on my dev machine. I've just been confident that it fails for reasons other than my code changes.  :-)

**Comment by daviwil** [comment]
Ahhh crap, I might need to look into that then.  It works by temporarily copying a profile file to the current user's profile path.  I suspect there's a timing issue with the test, might have to work on it a bit more.

**Comment by rkeithhill** [comment]
WRT PublishingScriptDiagnostics, that does indeed "clear" the current diagnostics but the new diagnostics that should be appearing are not.  Any ideas what I need to do on that?

**Comment by daviwil** [comment]
Instead of calling `PublishScriptDiagnostics` you could do this:

```csharp
this.RunScriptDiagnostics(
    this.editorSession.Workspace.GetOpenedFiles(),
    this.editorSession,
    eventContext);
```

**Comment by rkeithhill** [comment]
Should we still "clear" diagnostics first by calling PublishScriptDiagnostics or does RunScriptDiagnostics take care of clearing?

**Comment by daviwil** [comment]
Hmmm, maybe clearing first is a good idea just in case `RunScriptDiagnostics` fails to complete.

**Comment by rkeithhill** [comment]
Cool.  Now the diag records update when you change the settingsPath.  Note they do not change if you just update the settings file itself (we talked about file watchers but punted for now).  To work around this, you change the settingsPath value temporarily to something else and back to the original value.  Either that or you reload the window.

**Comment by daviwil** [comment]
Awesome!  Even though we couldn't get all the way there with the feature for this release, I think it's going to be pretty helpful.

**Comment by daviwil** [comment]
Looks good, merge when ready despite the test failure.

**Comment by rkeithhill** [comment]
How do I get my master submodules/PSScriptAnalyzer back in proper sync?  It is showing a SHA1 for status which it doesn't normally do:
```
193> git status
HEAD detached from 2df55e0
nothing to commit, working directory clean
194> git log --oneline --graph --decorate --max-count 15
*   e19af12 (HEAD, origin/master, master) Merge pull request #488 from PowerShell/development
|\
| *   5d9ff2b (origin/development, origin/HEAD) Merge pull request #487 from PowerShell/UpdateChangeLog
| |\
| | * 7109ab9 Update CHANGELOG.MD
| |/
* |   6b65076 Merge pull request #486 from PowerShell/development
```
When I switched back to master I went to that dir and executed `git pull origin master`.  Perhaps I should not have done??

**Comment by daviwil** [comment]
Here's what you need to do to fix it:

```
cd ..\.. (back to repo root)
git submodule sync
git submodule update
```

After that the submodule should be at the right head location.  Let me know if that doesn't work and I'll see if I can repro it on my end.

Did I mention the part where I hate submodules? :)

**Comment by rkeithhill** [comment]
No dice.  Same detached head status as before.

**Comment by daviwil** [comment]
Ahhh, sorry about that, I misunderstood.  Don't worry about the detached head state, that's just because we're synced to a specific commit in the submodule repo.  If you `cd ..\..` the Editor Services repo should be in a good state and the `submodules\PSScriptAnalyzer` submodule should not be in a 'changed' state anymore.  Is that what you see?

**Comment by rkeithhill** [comment]
Correct.   OK then no worries about that particular's directories detached head state. Cool.

**Pull request merged**
