### PR TITLE
Pulll reques

### PR DESCRIPTION
**Pull request by Bauerfilho**
# PR Summary

### CODE REVIEW

**Comment by JustinGrote** [comment]
I'm going to close this PR as it is not clear what you were trying to accomplish and looks like a mistake.

**Comment by Bauerfilho** [comment]
It is for my own development. I have only just begun learnings and power shell seems q good one to confine

**Comment by Bauerfilho** [comment]
Please don’t close, I think it’s the first one I did right

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Justin Grote ***@***.***>
Enviado: Monday, December 2, 2024 2:22:57 AM
Para: PowerShell/PowerShellEditorServices ***@***.***>
Cc: Bauerfilho ***@***.***>; Mention ***@***.***>
Assunto: Re: [PowerShell/PowerShellEditorServices] Pulll reques (PR #2204)


Closed #2204<https://github.com/PowerShell/PowerShellEditorServices/pull/2204>.

**Comment by JustinGrote** [comment]
@Bauerfilho what are you trying to accomplish with this PR? A pull request means you have some code that you wish to be merged into the PowerShellEditorServices extension. You need to explain that in the subject. It looks like you merged in some commits we've already merged, and added some sort of irrelevant java tasks.json.

image

I'm glad you're learning! But I do not feel this PR is what you were trying to accomplish. Here's more information about pull requests.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Review by Bauerfilho — COMMENTED** [review]
Aproves

**Comment by JustinGrote** [comment]
Ah, I see, well you don't have to ask permission for that because our license allows it by default!

To use PSES code in your own project, you simply need to abide to the terms of the MIT license. Essentially, make sure you just include a file somewhere that has a copy of our license file and note the attribution.

https://github.com/PowerShell/PowerShellEditorServices/blob/main/LICENSE

Here's more info about the MIT license and how to use code licensed by it.
https://snyk.io/learn/what-is-mit-license/

**Comment by Bauerfilho** [comment]
Thank you. I am a medical student. This is what i spend my time as a hobbie. I will study more to not cause troubles, since I have had same failures… In any case, have a great week.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Justin Grote ***@***.***>
Enviado: Monday, December 2, 2024 2:53:57 AM
Para: PowerShell/PowerShellEditorServices ***@***.***>
Cc: Bauerfilho ***@***.***>; Mention ***@***.***>
Assunto: Re: [PowerShell/PowerShellEditorServices] Request to use PSES code for my project (PR #2204)


Ah, I see, well you don't have to ask permission for that because our license allows it by default!

To use PSES code in your own project, you simply need to abide to the terms of the MIT license. Essentially, make sure you just include a file somewhere that has a copy of our license file and note the attribution.

https://github.com/PowerShell/PowerShellEditorServices/blob/main/LICENSE

Here's more info about the MIT license and how to use code licensed by it.
https://snyk.io/learn/what-is-mit-license/

**Pull request closed without merging**
