### PR TITLE
Pin Alpha versions of OmniSharp NuGet packages and adapt to new breaking changes

### PR DESCRIPTION
**Pull request by bergmeister**
The reason why the build is broken is because as per this [comment](https://github.com/PowerShell/PowerShellEditorServices/pull/1283/files#r430355321)
- You are accidentally using a PR artefact of `OmniSharp.Extensions.LanguageServer` and `OmniSharp.Extensions.DebugAdapter.Server` instead of the master build artefact
- Even once you prefix the nuget reference with `0.17.0-alpha*`, the build will still be broken because they made quite a few breaking changes between version `0.17.0-alpha-0015` (your last green build) and  `0.17.0-alpha-0017` . Lots of namespace renames only though

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/SignatureHelpHandler.cs  -1
+ src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs  -1
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/HoverHandler.cs  -1
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs  -1
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs  -1
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/FoldingRangeHandler.cs  -2
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs  -1
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/DefinitionHandler.cs  -1
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs  -1
+ src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/TylerLeonhardt/PowerShellEditorServices/pullRequest?prid=5585533&bid=18305283)

**Comment by TylerLeonhardt** [comment]
Those releases are for us to try and fix:

https://github.com/PowerShell/vscode-powershell/issues/2627

**Comment by bergmeister** [comment]
Just to double check we are on the same page:
Are you aware that with the current setup, you are consuming PR branch artefacts of the Omnisharp libraries instead of their latest pre-release/alpha version? I though this was unintentional because the last master build of PSES was using their latest alpha artefact (hence why I am pinning the latest alpha version in this PR),

**Comment by TylerLeonhardt** [comment]
The Omnisharp folks don't usually release a "PR branch artifact". They only manually did it for me so that I could test out their fixes in:

PowerShell/vscode-powershell#2627

I have a branch with all of the updated changes (all the breaking changes):
https://github.com/TylerLeonhardt/PowerShellEditorServices/tree/take-2-fix-lang-features-disappear

and am planning on sending a PR with these changes in the next day or so (so long as PowerShell/vscode-powershell#2627 is fixed)

I understand that the repo is in a bit of a bad state right now but PowerShell/vscode-powershell#2627 is such a bad bug that is affecting too many customers for me to focus on anything else at the moment.

**Comment by TylerLeonhardt** [comment]
In other words - give me a day or two and things will (hopefully) be back to normal 😅

**Comment by bergmeister** [comment]
OK, gotcha, at first it looked like it was unintentional. :-)
In retrospect, it might've been better to either not merge #1283 or rather pin the exact working version of the omnisharp libraries.

**Comment by TylerLeonhardt** [comment]
I'm gonna close this PR. We should pin once the next stable release is out but for now, we need to use *

**Pull request closed without merging**
