### PR TITLE
Remove PS 6.0 leftovers

### PR DESCRIPTION
**Pull request by bergmeister**

### CODE REVIEW

**Comment by bergmeister** [comment]
Thanks. Note that there seems to be a problem with the build though. This is not ready for merging yet

**Comment by bergmeister** [comment]
I had to revert one change to get it working as it seems that [this](https://github.com/PowerShell/PowerShellEditorServices/blob/master/PowerShellEditorServices.build.ps1#L106) piece of code is still needed, I guess the `6.0` key name is just a bit misleading, maybe just calling it `6` would be easier?

**Comment by rjmholt** [comment]
> I guess the 6.0 key name is just a bit misleading, maybe just calling it 6 would be easier?

We shouldn't need them, but you might not be able to just delete those lines -- there may be other build parts that assume their existence. If you remake that change I can take a look at the build

**Comment by rjmholt** [comment]
> @rjmholt didn't you fully qualify the PSReadLine call to get around a 6.0 issue?

Yeah, because 6.0 ships PSReadLine badly. So I think you're right that we should be able to unqualify that now

**Comment by TylerLeonhardt** [comment]
@bergmeister did you wanna put that change back in for Rob?

**Comment by bergmeister** [comment]
I think this change could already go in and the 2md change should be another PR, I just didn't have the time so far, so I suggest to create a tracking issue

**Comment by bergmeister** [comment]
Master has moved on so much that this code does not exist at all any more, closing :-)

**Pull request closed without merging**
