### PR TITLE
Import `PSDesiredStateConfiguration` by name

### PR DESCRIPTION
**Pull request by andyleejordan**
Resolve https://github.com/PowerShell/vscode-powershell/issues/3971.

Import PSDesiredStateConfiguration by name, not by hard-coded path, and clean-up some inconsistencies.

### CODE REVIEW

**Review by SeeminglyScience — APPROVED** [review]
LGTM!

**Comment by kborowinski** [comment]
@andyleejordan @SeeminglyScience  This causes the progress bar to show up and stay on, when using interactive debug session on PowerShell 5.1:

Animation

Could it be disabled with `$ProgressPreference = "SilentlyContinue"`?

**Comment by andyleejordan** [comment]
@kborowinski yes it can and seems to work well: https://github.com/PowerShell/PowerShellEditorServices/pull/2068

**Comment by kborowinski** [comment]
@andyleejordan Good find Andy!

**Pull request merged**
