### PR TITLE
A few minor fixes for the 0.4.0 release

### PR DESCRIPTION
**Pull request by daviwil**

### CODE REVIEW

**Comment by adamdriscoll** [comment]
Based on the amount of GitHub notifications I'm getting I would bet there is a release coming soon. ;)

**Comment by daviwil** [comment]
Yeeeeep ;)  Shooting for Monday!  We'll see when the VS Code team drops 0.10.7.

**Comment by adamdriscoll** [comment]
:metal:

**Comment by daviwil** [comment]
Nice, that emoji is awesome.

**Pull request merged**
