### PR TITLE
Fixes #196 - reorder messages to prevent dbgr fail to start

### LINKED ISSUE #196: Debug adapter doesn't complete startup sequence in VS Code 0.10.12-insiders
Looks like the 0.10.12-insiders release has broken us somehow.  The debug adapter starts but no output is written and pausing the debugger doesn't seem to work.  It seems like the script is never getting launched.  The only thing I see that's different is the added `noDebug` field in the launch request.  @rkeithhill, do you see anything in the following startup sequence that might cause a problem?

Here's the logs:

```
3/22/2016 7:18:02 AM [NORMAL] - Method "Main" at line 103 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host v0.5.0.304 starting (pid 11308)...

3/22/2016 7:18:02 AM [NORMAL] - Method "Main" at line 112 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host started!

3/22/2016 7:18:02 AM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 1,
      "command": "initialize",
      "arguments": {
        "adapterID": "PowerShell",
        "pathFormat": "path",
        "linesStartAt1": true,
        "columnsStartAt1": true
      }
    }

3/22/2016 7:18:02 AM [VERBOSE] - Method "WriteMessage" at line 58 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "initialized",
      "body": null
    }

3/22/2016 7:18:02 AM [VERBOSE] - Method "WriteMessage" at line 58 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": "1",
      "command": "initialize",
      "success": true,
      "body": {
        "supportsConfigurationDoneRequest": true,
        "supportsFunctionBreakpoints": true,
        "supportsConditionalBreakpoints": true,
        "supportsEvaluateForHovers": false
      }
    }

3/22/2016 7:18:02 AM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 2,
      "command": "launch",
      "arguments": {
        "name": "PowerShell",
        "type": "PowerShell",
        "request": "launch",
        "program": "c:\\Users\\daviwil\\.vscode-insiders\\extensions\\ms-vscode.PowerShell-0.5.0\\examples\\DebugTest.ps1",
        "args": [],
        "cwd": "c:\\Users\\daviwil\\.vscode-insiders\\extensions\\ms-vscode.PowerShell-0.5.0\\examples\\DebugTest.ps1",
        "noDebug": false
      }
    }

3/22/2016 7:18:02 AM [VERBOSE] - Method "HandleLaunchRequest" at line 143 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    Working dir set to: c:\Users\daviwil\.vscode-insiders\extensions\ms-vscode.PowerShell-0.5.0\examples

3/22/2016 7:18:02 AM [VERBOSE] - Method "WriteMessage" at line 58 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": "2",
      "command": "launch",
      "success": true,
      "body": null
    }

3/22/2016 7:18:10 AM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 3,
      "command": "pause",
      "arguments": {
        "threadId": 0
      }
    }

3/22/2016 7:18:10 AM [VERBOSE] - Method "BreakExecution" at line 529 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Debugger break requested...

3/22/2016 7:18:16 AM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 4,
      "command": "disconnect",
      "arguments": {
        "restart": false
      }
    }

3/22/2016 7:18:16 AM [VERBOSE] - Method "AbortExecution" at line 504 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Execution abort requested...
```

### PR DESCRIPTION
**Pull request by rkeithhill**
This commit sends the initialized event *after* the initializeRequest response (that sends capabilities info).  This was recommended by @isidorn in issue http://github.com/Microsoft/vscode/issues/4567.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershelleditorservices/204)

### CODE REVIEW

**Comment by daviwil** [comment]
Cool!  Looks like Andre is trying to figure out what the right sequence should be.  Should we wait on merging this until we know for sure what they want it to be?

**Comment by rkeithhill** [comment]
I'm fine with that.  It is a little disconcerting to me that this works in the Insider build but not the Alpha build.  Well, the debugger starts in the Alpha build - it just has that weird error after the debugger stops if you have paused the debugger at any point during the debug session.

**Comment by daviwil** [comment]
Where are you getting the alpha build?  Seems like the Insider build is the only one we should really be concerned with since the alpha builds are not generally available (as far as I know).

**Comment by rkeithhill** [comment]
I got a link to it a while back that I can't find anymore. Now I just copy that alpha installer around to various machines and it installs then updates to the latest.  It usually updates almost every day so I kind of like to use it as a bleeding edge test harness.  :-)

**Comment by daviwil** [comment]
Oh, interesting, didn't know that the Alpha build is actually updating itself.  Who knows what branch it's actually coming from...  I have been hearing that they're going to have some kind of public nightly build support for the Insiders release so maybe they're working up to that with this Alpha build.

**Comment by rkeithhill** [comment]
Do we want to keep waiting? I'm not seeing any movement on the VSCode side.  My alpha build still gives an error at the end of a debug **if** you have pressed paused at any point.  Otherwise it works fine which is better than the current behavior (without this PR) where debugging doesn't start at all.

**Comment by daviwil** [comment]
Yeah let's go ahead and merge it so that things won't be broken for a later release.  We can give some guidance in the release notes of our next version about the weird error that shows up in this case.  The logs you sent on the issue at the vscode repo make it seem like there's some timing issue they need to fix so I assume that will get resolved at some point.

**Pull request merged**
