### PR TITLE
Rename Microsoft.PowerShell.EditorServices.Host to Microsoft.PowerShell.EditorServices.Server

### PR DESCRIPTION
**Pull request by daviwil**
The new name more accurately reflects the role of this assembly in PowerShell Editor Services.  After the PSES-as-a-module change last year, PSES no longer a host but a server hosted inside of PowerShell that exposes services for the PowerShell language.

### CODE REVIEW

**Comment by daviwil** [comment]
Any strong objections to this?  Ultimately my goal is to ship the various components of PSES as separate modules on the Gallery so this naming seemed to be clearer.

**Comment by rkeithhill** [comment]
None from me.

**Comment by daviwil** [comment]
I think I might hold off on merging this until I consider some other options.

**Comment by daviwil** [comment]
Closing this for now.

**Pull request closed without merging**
