### PR TITLE
Format all files

### PR DESCRIPTION
**Pull request by dkattan**
There has been a general lack of convention for code formatting. Reformatted all code according to the .editorconfig to hopefully prevent unintentional whitespace changes in the future.

### CODE REVIEW

**Comment by andschwa** [comment]
Is there a way we can do this automatically and setup a GitHub action to keep the files formatted correctly?

**Comment by andschwa** [comment]
@dkattan It looks like we can do this using the built-in .NET Code analyzers: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#code-style-analysis

**Comment by panekj** [comment]
> Is there a way we can do this automatically and setup a GitHub action to keep the files formatted correctly?

https://github.com/nvuillam/mega-linter/blob/master/docs/descriptors/csharp_dotnet_format.md
+
https://github.com/nvuillam/mega-linter#apply-fixes

**Comment by dkattan** [comment]
I'd prefer for it to be done automatically as well. Perhaps this could be something @andschwa can steamroll while he overhauls CI/CD on this project? 😃

**Comment by dkattan** [comment]
Closing in favor of a CI action to perform formatting.

**Pull request closed without merging**
