### PR TITLE
Centralized Loading of Required Modules to PowerShellContextService.cs

### PR DESCRIPTION
**Pull request by dkattan**
The primary goal of this change is to make it easier to support runspaces without FileSystem providers. While this is a somewhat obscure use case, it benefits the codebase as a whole by consolidating various often inconsistent permutations of

```c#
PSCommand importCommand = new PSCommand()
                .AddCommand("Import-Module")
                .AddArgument(path);

            this.ExecuteCommandAsync<PSObject>(importCommand, sendOutputToHost: false, sendErrorToHost: false).ConfigureAwait(false).GetAwaiter().GetResult();
```
Into a single working copy. 

Summary of changes:
1. Created ImportModule(string path) method in PowerShellContextService.cs
2. Used method to load the Commands, PSReadLine, and additional modules
3. Moved the PowerShellEditorServices.Commands module to the modules folder so it could be loaded by its folder path instead of requiring a path to the .psm1 itself (this puts it in alignment with how we are doing PowerShellEditorServices.VSCode and how the Az module handles it's various sub-modules. I did this primarily because in the future when we support runspaces without FileSystem providers, we will need to use the InitialSessionState.ImportModuleFromPath() method, which only accepts folder paths and not paths to .psm1 files)
4. Updated CanGetPSReadLineProxy() test to work even though TryGetPSReadLineProxy() no longer Imports the module. We do this by exposing IsPSReadLineEnabled parameter in PowerShellContextFactory.Create() method and calling that method within CanGetPSReadLineProxy which creates an unused PowerShellContextService that Imports PSReadLine, thus loading the Microsoft.PowerShell.PSConsoleReadLine type into memory, allowing TryGetPSReadLineProxy to succeed

For reference, we are currently Importing modules from disk as needed in the following areas of the codebase:

https://github.com/PowerShell/PowerShellEditorServices/blob/00c78242e17a7265706a0fa07b67770709a670ac/src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs#L76-L78

https://github.com/PowerShell/PowerShellEditorServices/blob/00c78242e17a7265706a0fa07b67770709a670ac/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L240-L243

https://github.com/PowerShell/PowerShellEditorServices/blob/00c78242e17a7265706a0fa07b67770709a670ac/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L432-L434

These following module loading code has been left unmodified as they are not required modules and Import-Module is being used to determine if PSES has the stated capabilities.

https://github.com/PowerShell/PowerShellEditorServices/blob/3274c230cc6675859d5c89d6c176219c2c9430f7/src/PowerShellEditorServices/Services/PowerShellContext/TemplateService.cs#L94-L97

https://github.com/PowerShell/PowerShellEditorServices/blob/3274c230cc6675859d5c89d6c176219c2c9430f7/src/PowerShellEditorServices/Services/PowerShellContext/Session/Capabilities/DscBreakpointCapability.cs#L94-L100

### CODE REVIEW

**Comment by dkattan** [comment]
Hey @andschwa can you take a look at this CodeQL failure?

**Comment by andschwa** [comment]
> Hey @andschwa can you take a look at this CodeQL failure?

I'm just gonna re-run it 😅

**Comment by dkattan** [comment]
> > Hey @andschwa can you take a look at this CodeQL failure?
> 
> I'm just gonna re-run it 😅

Looks like it passed! You mind reviewing it?

**Comment by andschwa** [comment]
I'm so sorry, I haven't gotten to this yet. It'll be the first thing I look at after the next preview release.

**Comment by dkattan** [comment]
> Sorry we didn't get to this sooner @dkattan, it's in conflict now and it's _definitely_ going to be in conflict after https://github.com/PowerShell/PowerShellEditorServices/pull/1459. If you have the inclination, go ahead and take a look over there and see if you'll still need to make changes afterwards.

I was able to get everything working without modifying the codebase with the changes in 3.0. Closing this PR.

**Comment by andschwa** [comment]
@dkattan That's amazing! Thank you for your work and ideas, it was influential.

**Comment by andschwa** [comment]
@dkattan For real:

https://github.com/PowerShell/PowerShellEditorServices/blob/7bf4299a1210828a3bb11fee91d0c4924f074e98/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L748-L756

**Pull request closed without merging**
