### PR TITLE
Add `DoesNotDuplicateScriptMarkersAsync` regression test

### PR DESCRIPTION
**Pull request by andschwa**
This is a regression test for https://github.com/PowerShell/PowerShellEditorServices/pull/1869.

### CODE REVIEW

**Comment by andschwa** [comment]
@fflaten Hey look, a regression test! 🫡

**Review by SeeminglyScience — APPROVED** [review]
LGTM!

**Comment by fflaten** [comment]
Thanks! Didn't know where to start on that.

**Comment by andschwa** [comment]
> Thanks! Didn't know where to start on that.

No worries at all, I've been on a regression test roll.

**Pull request merged**
