### PR TITLE
Add tests ensuring tagged pester tests still register as pester symbols

### PR DESCRIPTION
**Pull request by rjmholt**
PSES currently only tests untagged Pester tests. This adds tests for recognising tagged Pester tests as Pester symbols.

This build should succeed with #638.

### CODE REVIEW

**Comment by rjmholt** [comment]
I noticed that the StopDebugger test is failing here too for some reason...

**Comment by rjmholt** [comment]
Oh, looks like it worked after being restarted

**Comment by tylerl0706** [comment]
So the test you wrote is failing. Is that on purpose?

**Comment by tylerl0706** [comment]
Oh I see. Need to do #638 first.

**Comment by tylerl0706** [comment]
whatcha trying to do there, @rjmholt 😄

**Comment by rjmholt** [comment]
Think I should have it now.

Was trying to restart the tests, but realised I needed to rebase onto master first. So have now done that. Hopefully the new test will now pass and we can merge this one too.

**Comment by rjmholt** [comment]
Hmmm, I may have botched this. I'll just go from the new `master`.

**Comment by tylerl0706** [comment]
To restart the tests you have to do into Travis and AppVeyor. I was manually restarting them for you :)

**Comment by rjmholt** [comment]
Yes, I was trying to go to AppVeyor and I couldn't work out how to restart the test. Eventually I decided to open and close the PR to try and get them to rerun. I can restart tests in Travis with no problems, but looked everywhere in AppVeyor and couldn't see it.

**Pull request closed without merging**
