### PR TITLE
Pass InitialSessionState instead of LanguageMode

### PR DESCRIPTION
**Pull request by dkattan**

### CODE REVIEW

**Comment by andschwa** [comment]
I like, I like. We should move the setting of execution policy to bypass in the ISS to happen _only_ in the test factory, since it shouldn't be necessary otherwise.

**Comment by dkattan** [comment]
> I like, I like. We should move the setting of execution policy to bypass in the ISS to happen _only_ in the test factory, since it shouldn't be necessary otherwise.

Done! All tests pass.

**Comment by rjmholt** [comment]
Closing in favour of https://github.com/PowerShell/PowerShellEditorServices/pull/1526

**Comment by andschwa** [comment]
Thanks @dkattan!

**Pull request closed without merging**
