### PR TITLE
Adds support for Linux and MacOS testing via Travis CI

### PR DESCRIPTION
**Pull request by PowerSchill**
This PR adds support for MacOS and Linux build tests via the Travis CI platform. Ubuntu Trusty and MacOS 10.12 are supported with this configuration. In addition the README was updated to include the build badge from Travis CI and also includes directions on installing OpenSSL on MacOS to support the build. 

The download.sh was copied from the PowerShell repo and updated for v6.0.0-beta.1.

This addresses the first part of testing mentioned in #461.

### CODE REVIEW

**Comment by daviwil** [comment]
Dude, thank you so much!  Only one suggestion, could you move `tools/travis.ps1` into `scripts/`?  Other than that, this is awesome, I really appreciate you setting this up!

**Comment by PowerSchill** [comment]
Sure thing. Do you want me to move download.sh as well?

**Comment by daviwil** [comment]
Yep!  Was blind and didn't see it was also in tools :)

**Comment by daviwil** [comment]
Thanks Mark!  Merging it :)

**Comment by PowerSchill** [comment]
I noticed the badge didn't update on README.md. I think you need to enable Travis CI for the repo for it to update.

**Comment by daviwil** [comment]
It's enabled for this repo, I think the problem is that the image link in the README uses `Powershell/PowerShellEditorServices` which has the wrong casing of `PowerShell`.  Looks like they are strict about that :)  Wanna send another PR to update it?

**Pull request merged**
