### PR TITLE
Add symbols for class-types and configuration

### LINKED ISSUE #1683: Classes should be symbols
image

### LINKED ISSUE #1905: Outline, symbol search and go to definition should jump to symbol name
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

```powershell
function
MyFunc123 {
    'some code'
}

MyFunc123
```

- Select the last line and press F12
- Find `MyFunc123` in symbol search
- Click in outline

### Expected behavior

```console
Jumps to line 2 `MyFun123` like other languages like C# and TypeScript
```

### Actual behavior

```console
Jumps to `function`
```

### Error details

_No response_

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

2022.8.3 preview

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by fflaten**
# PR Summary

Adds support for class-related symbols:
- Class
- Enum
- Property and EnumMember (no references) 
- Methods (no references)
- Constructors (no references)
- Configuration (no references/definition and highlight)

All symbol types have document symbols (outline + symbol search), symbol highlight and hover.
Only class and enum has code lense and references.

Methods and Constructors are shown with parameters in outline + workspace symbol search.

Also:
- Fixes symbol-detection when newline between function-keyword and name (#1905)
- Comment and code cleanup in relevant parts

TODO:
- [x] Manual test
- [x] Add tests

## PR Context

Easier navigation, search and sticky scroll.

Fix #1683
Fix #1905
Related #14 (fixed also? what is parameter hints?)
Related PowerShell/vscode-powershell#3 (missing references for class members)

### CODE REVIEW

**Comment by fflaten** [comment]
Do you prefer this PR being solely document symbols for outline/workspace search as a first step to keep PR size small, like in PowerShell-repo? Or should everything be implemented before merge and release? I personally just needed documentsymbols for a project.

I planned on implemented hover and highlight quickly, but highlight requires `FindReferencesVistor` also. So in the end I'd need to implement references/declaration and PR will grow + take time to figure out how to test it all. 😄 

Also just to make sure before I waste any time, @JustinGrote are you or someone else working on this already?

**Comment by JustinGrote** [comment]
> Also just to make sure before I waste any time, @JustinGrote are you or someone else working on this already? 

Nope I am not, this would be very welcome!

**Comment by SydneyhSmith** [comment]
> Do you prefer this PR being solely document symbols for outline/workspace search as a first step to keep PR size small, like in PowerShell-repo? Or should everything be implemented before merge and release? I personally just needed documentsymbols for a project.
> 
> I planned to implement hover and highlight quickly, but highlight requires `FindReferencesVistor` also. So in the end I'd need to implement references/declaration and PR will grow + take time to figure out how to test it all. 😄
> 
> Also just to make sure before I waste any time, @JustinGrote are you or someone else working on this already?

We generally probably prefer smaller PRs scoped to complete work items, however it depends on exactly what the scope of work is...what PRs/work items would you imagine being related to this work item? 

Thanks!

**Comment by fflaten** [comment]
> what PRs/work items would you imagine being related to this work item?

Ex. 
- Class-related document symbols (outline + workspace symbol search)
  - This PR + cleanup and tests - would consider it as a fix for #1683
- Class references/declarations (go to .. and codelense)
- Class-related symbol hover and highlight (on click)

Not sure if I can split any more because the AST-visitors are somewhat mixed together in some of the providers, so solve one -> solve many.

I'm already working on the remaining functionality in #14, so just wondering if I should start to consider how/if I can split it or if it's fine to let this PR grow.

**Comment by SeeminglyScience** [comment]
Thank you so much for gettin' the ball rollin' on this ❤️ 

> I planned to implement hover and highlight quickly, but highlight requires `FindReferencesVistor` also

Just a heads up that the engine doesn't really provide any sort of static type/member inference atm. So anything that requires tracking references might need to be deferred for a bit.

**Comment by fflaten** [comment]
> Just a heads up that the engine doesn't really provide any sort of static type/member inference atm. So anything that requires tracking references might need to be deferred for a bit.

I assume you're meaning properties, methods and constructors?

I only plan on tracking references for class/enum definitions against type constraints and expressions (`[typeName]`).

Custom classes are hopefully referenced with `Name` that is unique and not qualified. Same risk as duplicate functions in different scopes which PSES already get mixed.

image

**Comment by fflaten** [comment]
I'd like to start by apologizing for the mess 😄

I should've stopped at document symbols so I could break it down into multiple smaller PRs. Highlight basically required everything implemented at which point it made sense to refactor some code to avoid repeating it + avoid inconsistent symbol start-position (keyword vs name).

Ready for review. Not sure what's going on with the CodeQL check. MacOS failure is flaky test.

**Comment by andschwa** [comment]
I love it, but am going to wait for the next release as we'll want to put this through a preview for a bit!

**Comment by andschwa** [comment]
OMG @fflaten I had so much going on that this fell off my radar. I'm so sorry!

**Comment by fflaten** [comment]
> OMG @fflaten I had so much going on that this fell off my radar. I'm so sorry!

It happends, no worries 🙂 Would welcome some feedback as I assume there's parts that needs to be updated now.

**Comment by andschwa** [comment]
Merged by https://github.com/PowerShell/PowerShellEditorServices/pull/1984

**Pull request closed without merging**
