### PR TITLE
Split and clean up `LanguageServiceTests.cs`

### LINKED ISSUE #1445: Fix tests in `Language/LanguageServiceTests.cs`
This file has most of its tests in place, but there are a few that need fixing:

https://github.com/PowerShell/PowerShellEditorServices/blob/b8ad2c7f47ff2adafa1da45f5dcf4e762b10c753/test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs#L323-L324

https://github.com/PowerShell/PowerShellEditorServices/blob/b8ad2c7f47ff2adafa1da45f5dcf4e762b10c753/test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs#L337-L338

https://github.com/PowerShell/PowerShellEditorServices/blob/b8ad2c7f47ff2adafa1da45f5dcf4e762b10c753/test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs#L411-L416

### PR DESCRIPTION
**Pull request by andschwa**
Since it now covers the symbols service and completions handler separately. Resolves #1445.

### CODE REVIEW

**Comment by andschwa** [comment]
@SeeminglyScience @rjmholt Please look at that last commit carefully: I've resurrected really old code to support aliases when finding references, and re-enabled the corresponding test.

**Comment by andschwa** [comment]
> @SeeminglyScience @rjmholt Please look at that last commit carefully: I've resurrected really old code to support aliases when finding references, and re-enabled the corresponding test.

I've actually removed that from this PR and have made it a new PR #1656 after cleaning it up.

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Comment by andschwa** [comment]
Thanks @daxian-dbw!

**Pull request merged**
