### PR TITLE
Add support for finding and installing PowerShell Gallery modules

### PR DESCRIPTION
**Pull request by dfinke**
Enables execution of Find-Module, then the displaying of modules in a quick pick list, if one is selected, Install-Module is then invoked

### CODE REVIEW

**Comment by daviwil** [comment]
Strange, how did we end up with Initial Commit twice?

**Comment by dfinke** [comment]
I should have labelled the `Initial commit` messages with `Find...` and `Install...`.

I'll look at using the `PSModuleMessage` too.

**Comment by daviwil** [comment]
Ahhhh ok, I thought the same commit got in there twice somehow :)  No problem!

**Comment by daviwil** [comment]
The changes look good!  Can you rebase your branch so that my commit doesn't show up twice in the commit history?  Here's the commands you'll need to use:

```
git reset origin/master
git add -A
git commit
git push -f origin spike-dcf-gallery
```

**Comment by dfinke** [comment]
I get this error.

```
git push -f origin spike-dcf-gallery

error: src refspec spike-dcf-gallery does not match any.
error: failed to push some refs to 'https://github.com/PowerShell/PowerShellEditorServices.git'
```

**Comment by daviwil** [comment]
Yep, I realized I made a mistake and edited my previous comment, the branch name should be `spike-dcf-psgallery`

**Pull request merged**
